### ISSUE TITLE
The close button on an annotation cannot be clicked

### ISSUE THREAD

**Issue by isaackd** [isaackd/AnnotationsRestored#23]
![dgwz4typcl](https://user-images.githubusercontent.com/24992665/51576686-39294380-1e85-11e9-9a28-0a2d5d934280.gif)

**Comment by afrmtbl** [comment]
Turns out only chrome has this problem
Most likely related to https://github.com/afrmtbl/AnnotationsRestored/issues/35

**Comment by achmadsutardi441953** [comment]
close button on an annotation cannot be clicked on chrome

**Comment by achmadsutardi441953** [comment]
> Turns out it works on Firefox
> Most likely related to #35
close button on an annotation cannot be clicked on chrome

**Comment by isaackd** [comment]
Should be fixed with [d4e2ac61906c64035a44287746ba37895da9c8db](https://github.com/isaackd/annotationlib/commit/d4e2ac61906c64035a44287746ba37895da9c8db) :tada:
