### ISSUE TITLE
Cache annotations until restart (enhancement)

### ISSUE THREAD

**Issue by T0biasCZe** [isaackd/AnnotationsRestored#42]
add option to cache the annotations data until the browser is restarted. in some of interactive videos you come back a lot when you choosed a wrong path, and everytime you go back the data needs to be found and redownloaded, which takes some time.
with option  to cache, it wouldnt need to be downloaded again and you dont need to wait 20 seconds xd

**Comment by isaackd** [comment]
Annotation files are now automatically cached as you watch. I made it so that the cache never expires and you can clear it manually by clicking "Manage Cache" in the popup. Thanks for the comment!
