### ISSUE TITLE
Extension gives reoccuring pop ups about videos not having annotations when used together with YouTube Auto HD + FPS (Firefox)

### ISSUE THREAD

**Issue by Lyckra** [isaackd/AnnotationsRestored#45]
![Capture](https://user-images.githubusercontent.com/52036629/126810284-6ac5e9b3-8719-4b4a-aa0f-0ed276fcba83.png)

**Comment by isaackd** [comment]
Without having looked into this yet, it sounds like the extension is trying to click the settings button to change the quality and ends up clicking the annotations button over and over. I'll see what I can do!

**Comment by isaackd** [comment]
The annotations button has now been removed and replaced with a popup page.
This should be fixed now, but let me know if there are any more issues between these extensions and I can check it out.
