### ISSUE TITLE
close button doesn't work at all

### ISSUE THREAD

**Issue by TorutheRedFox** [isaackd/AnnotationsRestored#55]
All the close button does is appear when you hover over the annotation itself. It disappears when your mouse leaves the main body of the annotation but not the button's body, making it tough to click, but not like that matters as you can't click on it at all, even when it's showing.

**Comment by isaackd** [comment]
Sorry for the long wait! Should be fixed with [d4e2ac61906c64035a44287746ba37895da9c8db](https://github.com/isaackd/annotationlib/commit/d4e2ac61906c64035a44287746ba37895da9c8db) :tada:
Now to upload the new version to the web stores.

**Comment by isaackd** [comment]
Version 1.2 is now available :)
