### ISSUE TITLE
YouTube added a new settings toggle named "Annotations"

### ISSUE THREAD

**Issue by isaackd** [isaackd/AnnotationsRestored#56]
![Screenshot from 2022-03-28 17-13-37](https://user-images.githubusercontent.com/24992665/160488332-1d2e934a-1048-4a62-9bfd-293ece9272d6.png)

Ours will need to be renamed or moved.

**Comment by TorutheRedFox** [comment]
wasn't the annotations toggle always there for channels that have the player branding icon? (with the toggle enabling/disabling said icon)

**Comment by isaackd** [comment]
Hmm I'm not sure if it was always there I've only noticed it more recently. I may have missed it when this feature was being added though.

**Comment by isaackd** [comment]
Our toggle was renamed to "Restore Annotations"

**Comment by TorutheRedFox** [comment]
> wasn't the annotations toggle always there for channels that have the player branding icon? (with the toggle enabling/disabling said icon)

afaik the branding icon is considered an annotation, with what is generally known as annotations having been "legacy" annotations prior to their removal (they seemingly never expanded on the newer annotations but they did seem to have further functionality past just adding an icon as it was defined in an xml file that defines nothing but the icon)
