### ISSUE TITLE
Extension stopped working

### ISSUE THREAD

**Issue by randomperson189** [isaackd/AnnotationsRestored#57]
For some reason recently this extension stopped working, I go to videos where they should show annotations but they don't and I wait there for like 5 minutes. I also have show annotations checked and I'm using Chrome btw. Other people seem to have been reporting this issue so it's not a me thing.

**Comment by isaackd** [comment]
I made a little mistake with the CORS configuration but it should be working again now. If it isn't working for you still I'd be happy to look into it some more!
