### ISSUE TITLE
Incorrect behavior on qepEaDnsGuU

### ISSUE THREAD

**Issue by Danfun64** [isaackd/AnnotationsRestored#64]
I'm not sure that anything can be done about this, because I distinctly remember this video being broken some time before annotations were completely removed. 

Around the 1:07-1:13 of [this](https://www.youtube.com/watch?v=qepEaDnsGuU) video, a box covers the top left of the screen. Originally there was text like, directly below the box. I believe it said something like "Yeah, no way of telling whatsoever." I'm not sure if the original text for that section is archived or not. The rest of the video is fine, and I'm happy to be able to see its annotations again. It's just that section IIRC. And like I said, it got broke before annotation support was removed, so I don't know if this can be fixed or not, but I'd love it if this issue could be fixed, in this video and any other videos that did the same thing.

**Comment by isaackd** [comment]
Hey! I checked out the annotation file and it does look like there should be text connected to the box but it's not there. Usually a `highlight` annotation will have a corresponding `highlightText` annotation that specifies the hover text. I think it may be lost unfortunately :/

**Comment by Danfun64** [comment]
Unfortunately I don't remember the exact text. I guess that's all that can be done. Thanks for checking though!
